apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: dexconfigurations.kubic.opensuse.org
spec:
  group: kubic.opensuse.org
  names:
    kind: DexConfiguration
    plural: dexconfigurations
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            adminGroup:
              type: string
            certificate:
              type: object
            image:
              type: string
            names:
              items:
                type: string
              type: array
            nodePort:
              format: int64
              type: integer
            replicas:
              format: int64
              type: integer
            staticClients:
              items:
                properties:
                  name:
                    type: string
                  public:
                    type: boolean
                  redirectURLs:
                    items:
                      type: string
                    type: array
                type: object
              type: array
          type: object
        status:
          properties:
            config:
              type: string
            deployment:
              type: string
            generatedCertificate:
              type: object
            numConnectors:
              format: int64
              type: integer
            staticClients:
              items:
                properties:
                  name:
                    type: string
                  password:
                    type: object
                  public:
                    type: boolean
                  redirectURLs:
                    items:
                      type: string
                    type: array
                type: object
              type: array
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
